// auto-generated by scripts/discoverEndpoints.js
export const endpoints = {
  "admin": [
    {
      "name": "takedown",
      "method": "PATCH",
      "path": "/admin/takedown",
      "validators": [
        {
          "body": [
            "entity_type",
            "entity_id"
          ],
          "params": [],
          "query": []
        }
      ],
      "auth": true
    }
  ],
  "announcements": [
    {
      "name": "getAllAnnouncements",
      "method": "GET",
      "path": "/announcements",
      "validators": [
        {
          "body": [],
          "params": [],
          "query": [
            "club_id",
            "target",
            "limit",
            "offset"
          ]
        }
      ],
      "auth": true
    },
    {
      "name": "getAnnouncementById",
      "method": "GET",
      "path": "/announcements/:id",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "createAnnouncement",
      "method": "POST",
      "path": "/announcements",
      "validators": [
        {
          "body": [
            "club_id",
            "title",
            "content_html",
            "target"
          ],
          "params": [],
          "query": []
        }
      ],
      "auth": true
    }
  ],
  "authentications": [
    {
      "name": "login",
      "method": "POST",
      "path": "/auth/login",
      "validators": [
        {
          "body": [
            "email",
            "password"
          ],
          "params": [],
          "query": []
        }
      ],
      "auth": false
    },
    {
      "name": "register",
      "method": "POST",
      "path": "/auth/register",
      "validators": [
        {
          "body": [
            "name",
            "email",
            "password"
          ],
          "params": [],
          "query": []
        }
      ],
      "auth": false
    }
  ],
  "clubs": [
    {
      "name": "listClubs",
      "method": "GET",
      "path": "/clubs",
      "validators": [
        {
          "body": [],
          "params": [],
          "query": [
            "search",
            "tag",
            "day"
          ]
        }
      ],
      "auth": true
    },
    {
      "name": "createClub",
      "method": "POST",
      "path": "/clubs",
      "validators": [
        {
          "body": [
            "name",
            "slug",
            "description",
            "advisor_name"
          ],
          "params": [],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "patchClub",
      "method": "PATCH",
      "path": "/clubs/:id",
      "validators": [
        {
          "body": [
            "name",
            "slug",
            "description",
            "logo_url",
            "banner_url",
            "advisor_name"
          ],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "joinClub",
      "method": "POST",
      "path": "/clubs/:id/join",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "setMemberStatus",
      "method": "PATCH",
      "path": "/clubs/:id/members/:userId",
      "validators": [
        {
          "body": [
            "decision"
          ],
          "params": [
            "id",
            "userId"
          ],
          "query": []
        }
      ],
      "auth": true
    }
  ],
  "events": [
    {
      "name": "listEvents",
      "method": "GET",
      "path": "/clubs/:id/events",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "createEvent",
      "method": "POST",
      "path": "/clubs/:id/events",
      "validators": [
        {
          "body": [
            "title",
            "description",
            "location",
            "start_at",
            "end_at",
            "capacity",
            "require_rsvp",
            "visibility"
          ],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "rsvpEvent",
      "method": "POST",
      "path": "/events/:id/rsvp",
      "validators": [
        {
          "body": [
            "status"
          ],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "reviewEvent",
      "method": "POST",
      "path": "/events/:id/review",
      "validators": [
        {
          "body": [
            "rating",
            "comment"
          ],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "checkinEvent",
      "method": "POST",
      "path": "/events/:id/checkin",
      "validators": [
        {
          "body": [
            "code"
          ],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    }
  ],
  "notifications": [
    {
      "name": "listNotifications",
      "method": "GET",
      "path": "/notifications",
      "validators": [
        {
          "body": [],
          "params": [],
          "query": [
            "page",
            "limit",
            "status",
            "type"
          ]
        }
      ],
      "auth": true
    }
  ],
  "posts": [
    {
      "name": "listPosts",
      "method": "GET",
      "path": "/clubs/:id/posts",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "getPostById",
      "method": "GET",
      "path": "/clubs/:id/posts/:postId",
      "validators": [
        {
          "body": [],
          "params": [
            "id",
            "postId"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "createPost",
      "method": "POST",
      "path": "/clubs/:id/posts",
      "validators": [
        {
          "body": [
            "body_html",
            "visibility",
            "pinned",
            "attachments"
          ],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    }
  ]
}
