// auto-generated by scripts/discoverEndpoints.js
export const endpoints = {
  "admin": [
    {
      "name": "takedown",
      "method": "PATCH",
      "path": "/admin/takedown",
      "validators": [
        {
          "body": [
            "entity_type",
            "entity_id"
          ],
          "params": [],
          "query": []
        }
      ],
      "auth": true
    }
  ],
  "announcements": [
    {
      "name": "getAllAnnouncements",
      "method": "GET",
      "path": "/announcements",
      "validators": [
        {
          "body": [],
          "params": [],
          "query": [
            "search",
            "limit",
            "offset"
          ]
        }
      ],
      "auth": false
    },
    {
      "name": "getAnnouncementById",
      "method": "GET",
      "path": "/announcements/:id",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": false
    },
    {
      "name": "createAnnouncement",
      "method": "POST",
      "path": "/announcements",
      "validators": [
        {
          "body": [
            "title",
            "content_html"
          ],
          "params": [],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "updateAnnouncement",
      "method": "PUT",
      "path": "/announcements/:id",
      "validators": [
        {
          "body": [
            "title",
            "content_html"
          ],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "deleteAnnouncement",
      "method": "DELETE",
      "path": "/announcements/:id",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    }
  ],
  "authentications": [
    {
      "name": "login",
      "method": "POST",
      "path": "/auth/login",
      "validators": [
        {
          "body": [
            "email",
            "password"
          ],
          "params": [],
          "query": []
        }
      ],
      "auth": false
    },
    {
      "name": "register",
      "method": "POST",
      "path": "/auth/register",
      "validators": [
        {
          "body": [
            "name",
            "email",
            "password"
          ],
          "params": [],
          "query": []
        }
      ],
      "auth": false
    },
    {
      "name": "me",
      "method": "GET",
      "path": "/auth/me",
      "validators": [],
      "auth": true
    }
  ],
  "clubs": [
    {
      "name": "listClubs",
      "method": "GET",
      "path": "/clubs",
      "validators": [
        {
          "body": [],
          "params": [],
          "query": [
            "search",
            "tag",
            "day",
            "membership"
          ]
        }
      ],
      "auth": true
    },
    {
      "name": "getClub",
      "method": "GET",
      "path": "/clubs/:id",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "createClub",
      "method": "POST",
      "path": "/clubs",
      "validators": [
        {
          "body": [
            "name",
            "slug",
            "description",
            "advisor_name"
          ],
          "params": [],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "patchClub",
      "method": "PATCH",
      "path": "/clubs/:id",
      "validators": [
        {
          "body": [
            "name",
            "slug",
            "description",
            "logo_url",
            "banner_url",
            "advisor_name"
          ],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "deleteClub",
      "method": "DELETE",
      "path": "/clubs/:id",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "joinClub",
      "method": "POST",
      "path": "/clubs/:id/join",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "leaveClub",
      "method": "DELETE",
      "path": "/clubs/:id/join",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "listMembers",
      "method": "GET",
      "path": "/clubs/:id/members",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "listJoinRequests",
      "method": "GET",
      "path": "/clubs/:id/requests",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "setMemberStatus",
      "method": "PATCH",
      "path": "/clubs/:id/members/:userId",
      "validators": [
        {
          "body": [
            "decision"
          ],
          "params": [
            "id",
            "userId"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "setMemberRole",
      "method": "PATCH",
      "path": "/clubs/:id/members/:userId/role",
      "validators": [
        {
          "body": [
            "role"
          ],
          "params": [
            "id",
            "userId"
          ],
          "query": []
        }
      ],
      "auth": true
    }
  ],
  "events": [
    {
      "name": "listAllEvents",
      "method": "GET",
      "path": "/events",
      "validators": [],
      "auth": true
    },
    {
      "name": "getEvent",
      "method": "GET",
      "path": "/events/:id",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "listEvents",
      "method": "GET",
      "path": "/clubs/:id/events",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "createEvent",
      "method": "POST",
      "path": "/clubs/:id/events",
      "validators": [
        {
          "body": [
            "title",
            "description",
            "location",
            "start_at",
            "end_at",
            "capacity",
            "require_rsvp",
            "visibility",
            "image_url"
          ],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "updateEvent",
      "method": "PUT",
      "path": "/events/:id",
      "validators": [
        {
          "body": [
            "title",
            "description",
            "location",
            "start_at",
            "end_at",
            "capacity",
            "require_rsvp",
            "visibility",
            "image_url"
          ],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "deleteEvent",
      "method": "DELETE",
      "path": "/events/:id",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "rsvpEvent",
      "method": "POST",
      "path": "/events/:id/rsvp",
      "validators": [
        {
          "body": [
            "status"
          ],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "reviewEvent",
      "method": "POST",
      "path": "/events/:id/review",
      "validators": [
        {
          "body": [
            "rating",
            "comment"
          ],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "checkinEvent",
      "method": "POST",
      "path": "/events/:id/checkin",
      "validators": [
        {
          "body": [
            "code"
          ],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    }
  ],
  "notifications": [
    {
      "name": "listNotifications",
      "method": "GET",
      "path": "/notifications",
      "validators": [
        {
          "body": [],
          "params": [],
          "query": [
            "page",
            "limit",
            "status",
            "type"
          ]
        }
      ],
      "auth": true
    }
  ],
  "posts": [
    {
      "name": "listPosts",
      "method": "GET",
      "path": "/clubs/:id/posts",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "getPost",
      "method": "GET",
      "path": "/posts/:id",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "getPostById",
      "method": "GET",
      "path": "/clubs/:id/posts/:postId",
      "validators": [
        {
          "body": [],
          "params": [
            "id",
            "postId"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "createPost",
      "method": "POST",
      "path": "/clubs/:id/posts",
      "validators": [
        {
          "body": [
            "body_html",
            "visibility",
            "pinned",
            "images"
          ],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "likePost",
      "method": "POST",
      "path": "/posts/:id/likes",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "unlikePost",
      "method": "DELETE",
      "path": "/posts/:id/likes",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "listComments",
      "method": "GET",
      "path": "/posts/:id/comments",
      "validators": [
        {
          "body": [],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "createComment",
      "method": "POST",
      "path": "/posts/:id/comments",
      "validators": [
        {
          "body": [
            "body_html"
          ],
          "params": [
            "id"
          ],
          "query": []
        }
      ],
      "auth": true
    }
  ],
  "clubCategories": [
    {
      "name": "listCategories",
      "method": "GET",
      "path": "/club-categories",
      "validators": [
        {
          "body": [],
          "params": [],
          "query": ["withClubs"]
        }
      ],
      "auth": true
    },
    {
      "name": "createCategory",
      "method": "POST",
      "path": "/club-categories",
      "validators": [
        {
          "body": ["name"],
          "params": [],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "patchCategory",
      "method": "PATCH",
      "path": "/club-categories/:id",
      "validators": [
        {
          "body": ["name"],
          "params": ["id"],
          "query": []
        }
      ],
      "auth": true
    },
    {
      "name": "deleteCategory",
      "method": "DELETE",
      "path": "/club-categories/:id",
      "validators": [
        {
          "body": [],
          "params": ["id"],
          "query": []
        }
      ],
      "auth": true
    }
  ]
}
